service: crud-users-serverless

provider:
  name: aws
  runtime: nodejs14.x
  iam:
    role:
      statements:
        - Effect: "Allow"
          Action: "dynamodb:*"
          Resource: "arn:aws:dynamodb:us-east-1:469286914666:table/usersTable"

package: 
  individually: true
  patterns:
    - "!.dynamodb/**"
    - "!node_modules/**"
    - "!venv/**"

plugins:
  - serverless-dynamodb
  - serverless-offline
  - serverless-dotenv-plugin
custom:
  serverless-dynamodb:
  # If you only want to use DynamoDB Local in some stages, declare them here
    stages:
      - dev
    start:
      port: 8000
      inMemory: true
      heapInitial: 200m
      heapMax: 1g
      migrate: true
      seed: true
      convertEmptyValues: true

functions:
  get-user-by-id:
    handler: src/functions/getUserById/handler.getUserById
    timeout: 20
    events:
      - http:
          path: users/{id}
          method: GET
  get-users:
    handler: src/functions/getAllUsers/handler.get_users
    runtime: python3.8
    timeout: 30
    events:
      - http:
          path: users
          method: GET
  create-user:
    handler: src/functions/createUsers/handler.createUsers
    timeout: 20
    events:
      - http:
          path: users
          method: POST
resources:
  Resources:
    usersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: usersTable
        AttributeDefinitions:
          - AttributeName: pk
            AttributeType: S
        KeySchema:
          - AttributeName: pk
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1