service: crud-users-serverless

provider:
  name: aws
  runtime: nodejs14.x

functions:
  hello-world:
    handler: handler.hello
    events:
      - http:
          path: hello
          method: GET
